#!/usr/bin/env python3
"""
bundle.py: build assets/bundle.js, the fallback that lets the site open from a
folder.

Every page here is markup plus data. assets/site.js fetches from data/ at load
time, which is what plan section 8 asks for so that regenerating data never
touches markup. The cost is that a browser gives a file:// page an opaque origin
and blocks fetch(), so double-clicking a page left every data-driven block
showing an error and every diagram missing. Until now the site's answer to that
was a banner telling the reader to start a server.

That is a real answer for a contributor and a poor one for the audience. Someone
handed a zip of this site should be able to open index.html and read it.

So: this writes one file containing analysis.json, every JSON file in data/ and
every SVG in assets/diagrams/, keyed by the path site.js would have fetched. site.js consults
it only when fetch() is unavailable or fails, so a served copy is completely
unaffected and data/ remains the single source of truth.

The bundle is generated and must never be hand-edited. verify.py --bundle
rebuilds it and fails on any difference, which is what stops it from drifting
away from the data it mirrors and quietly serving a reader stale content.

    python tools/bundle.py
    python tools/bundle.py --check     exit 1 if the committed bundle is stale
"""

from __future__ import annotations

import argparse
import datetime as _dt
import glob
import json
import os
import sys

TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))
SITE_ROOT = os.path.dirname(TOOLS_DIR)
DATA = os.path.join(SITE_ROOT, "data")
DIAGRAMS = os.path.join(SITE_ROOT, "assets", "diagrams")
OUT = os.path.join(SITE_ROOT, "assets", "bundle.js")

HEADER = """\
/* assets/bundle.js: GENERATED by tools/bundle.py. Do not edit.
 *
 * Analysis metadata, every JSON file in data/ and every SVG in assets/diagrams/,
 * keyed by the path assets/site.js would otherwise fetch. site.js reads this only when fetch() is
 * unavailable, which in practice means the page was opened from a folder rather
 * than served. A served copy never touches it.
 *
 * data/ remains the source of truth. This file mirrors it, and
 * tools/verify.py --bundle rebuilds it and fails on any difference, so a stale
 * mirror is a build failure rather than a page that quietly shows old content.
 *
 * Regenerate:  python tools/bundle.py
 * Files: %(files)d.  Generated from data/ at %(when)s.
 */
"""


def collect() -> dict:
    payload: dict = {}
    with open(os.path.join(SITE_ROOT, "analysis.json"), encoding="utf-8") as fh:
        payload["analysis.json"] = json.load(fh)
    for path in sorted(glob.glob(os.path.join(DATA, "**", "*.json"), recursive=True)):
        rel = os.path.relpath(path, SITE_ROOT).replace(os.sep, "/")
        with open(path, "r", encoding="utf-8") as fh:
            payload[rel] = json.load(fh)
    for path in sorted(glob.glob(os.path.join(DIAGRAMS, "*.svg"))):
        rel = os.path.relpath(path, SITE_ROOT).replace(os.sep, "/")
        with open(path, "r", encoding="utf-8") as fh:
            payload[rel] = fh.read()
    return payload


def render(payload: dict, when: str) -> str:
    body = json.dumps(payload, ensure_ascii=False, sort_keys=True,
                      separators=(",", ":"))
    head = HEADER % {"files": len(payload), "when": when}
    return f"{head}window.TFGBundle = {body};\n"


def build(check_only: bool = False) -> int:
    payload = collect()

    # The timestamp is the one thing that would change on every run, and a
    # generator that is not idempotent cannot be checked by regenerating and
    # diffing, which is how the workflow catches a generated file that was edited
    # by hand. So the previous timestamp is kept whenever the payload has not
    # changed, and only moves when the content does.
    now = _dt.datetime.now(_dt.timezone.utc).replace(microsecond=0).isoformat()
    when = now
    previous = None
    if os.path.isfile(OUT):
        existing = open(OUT, encoding="utf-8").read()
        for line in existing.splitlines():
            if "Generated from data/ at " in line:
                previous = line.split("Generated from data/ at ")[1].rstrip(". */").strip()
                break
        if previous and render(payload, previous) == existing:
            when = previous

    text = render(payload, when)

    if check_only:
        if not os.path.isfile(OUT):
            print(f"bundle.js is missing. Run: python tools/bundle.py", file=sys.stderr)
            return 1
        current = open(OUT, encoding="utf-8").read()
        if current != text:
            print("bundle.js is stale: analysis.json, data/ or assets/diagrams/ has changed "
                  "since it was generated.\nRun: python tools/bundle.py",
                  file=sys.stderr)
            return 1
        print(f"bundle.js is current, {len(payload)} files")
        return 0

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    size = os.path.getsize(OUT)
    print(f"assets/bundle.js  {len(payload)} files  {size:,} bytes")
    return 0


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check", action="store_true",
                   help="exit 1 if the committed bundle does not match data/")
    args = p.parse_args()
    sys.exit(build(check_only=args.check))


if __name__ == "__main__":
    main()
