#!/usr/bin/env python3
"""
tools/oscal_artifacts.py: author data/oscal-artifacts.json.

WHY THIS EXISTS. The walkthrough encodes two rules ourselves, so the pages argue
from content nobody published. That is the right trade for comparing modelling,
but it leaves a reader with no way to see what the three groups have actually
shipped. This inventory is that: every OSCAL document in the three corpora, what
model it is, and what is in it, counted from the file rather than described. The
fourth approach has shipped nothing, and its section says so.

Nothing here is authored. Every number is read off disk.
"""

import json, os, sys, glob, collections, urllib.parse

import extract as ex        # same directory

TOOLS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(TOOLS)
CORPORA = ex.corpora_root()
OUT = os.path.join(ROOT, "data", "oscal-artifacts.json")

#  Labelled by approach, not by publisher.
#
#  This page named the three groups, and was the one page on the site exempt
#  from the rule that no proponent organization appears in any prose, on the
#  argument that an inventory redacting the publisher would be useless. The
#  exemption is gone: an inventory of what each approach ships is just as
#  useful, and every other page has been talking about approaches for weeks
#  while this one talked about companies.
#
#  The repository link stays. It is a reference to a public location rather than
#  an attribution in prose, and without it a reader cannot go and check the
#  counts on this page against the files.
#
#  The directory each corpus is read from keeps its real name, because it is a
#  path on disk. It is not rendered.
PUBLISHERS = [
    ("catalog-first", "Catalog-first", "Option A",
     "AWS/oscal-content-for-aws-services-main",
     "https://github.com/awslabs/oscal-content-for-aws-services",
     "Option A"),
    ("component-first", "Component-first", "Option B", "IBM", None, "Option B"),
    ("assessment-first", "Assessment-first", "Option C", "Easy Dynamics", None,
     "Option C"),
    #  No corpus of its proponent's. The fourth approach is a concept note,
    #  and the corpus directory is None so the corpora scan is skipped. What
    #  is scanned for it instead is the corpus this repository generates in
    #  the note's shape, named in SITE_CORPORA, and the page says so.
    ("executable-first", "Executable-first", "Option D", None, None, "Option D"),
]

#  A corpus held in this repository rather than beside it, relative to the
#  site root. tools/executable_first_corpus.py writes it from the guidance under
#  sources/, and the inventory counts it like any other while the note says
#  whose it is.
SITE_CORPORA = {"executable-first": os.path.join("examples", "executable-first", "oscal")}

#  What an approach with no proponent's publication says on the inventory
#  page, and the one document its proponent does have. Held here beside the
#  list of publishers because the page has to say what the rows are, and
#  "generated here" is a fact about the approach rather than about the scan.
UNPUBLISHED = {
    "executable-first": {
        "note": ("No proponent has published OSCAL for this approach. What "
                 "exists is a concept note, linked below, and the documents "
                 "listed here were generated by tools/executable_first_corpus.py "
                 "from the CIS Benchmark and the DISA STIG for Ubuntu 24.04 in "
                 "the shape the note proposes. They are counted like any other "
                 "corpus and they are the site's, not a proponent's."),
        "document": {
            "href": "examples/executable-first/executable-assessment-methods.md",
            "label": ("Executable Assessment Methods, a concept note, September "
                      "2026"),
        },
    },
}

MODEL_LABEL = {
    "catalog": "Catalog",
    "profile": "Profile",
    "component-definition": "Component definition",
    "system-security-plan": "System security plan",
    "assessment-plan": "Assessment plan",
    "assessment-results": "Assessment results",
    "plan-of-action-and-milestones": "POA&M",
    "mapping-collection": "Mapping collection",
}


def summarise(model, body):
    """What is in the document, counted. One short phrase, never a judgement."""
    n = collections.OrderedDict()
    if model == "catalog":
        groups = body.get("groups", [])
        n["groups"] = len(groups)
        #  Controls at any depth. One catalog here nests groups three deep
        #  and keeps every control at the bottom, and a count of the top level
        #  alone would read as a catalog with no controls at all.

        def controls_in(gs):
            return sum(len(g.get("controls", [])) + controls_in(g.get("groups", []))
                       for g in gs)

        n["controls"] = controls_in(groups) + len(body.get("controls", []))
    elif model == "component-definition":
        comps = body.get("components", [])
        n["components"] = len(comps)
        by = collections.Counter(c.get("type", "?") for c in comps)
        for k in sorted(by):
            n[k] = by[k]
        rules = sum(len(c.get("rules", [])) for c in comps)
        if rules:
            n["rules"] = rules
        #  The Rules-shape assembly the generated corpus carries. Counted
        #  where present, like the other proposed assemblies, and named by
        #  the field.
        scripts = sum(len(ir.get("automation-scripts", []))
                      for c in comps for ci in c.get("control-implementations", [])
                      for ir in ci.get("implemented-requirements", []))
        if scripts:
            n["automation scripts"] = scripts
        irs = sum(len(ci.get("implemented-requirements", []))
                  for c in comps for ci in c.get("control-implementations", []))
        if irs:
            n["implemented requirements"] = irs
    elif model == "assessment-plan":
        ld = body.get("local-definitions", {}) or {}
        n["activities"] = len(ld.get("activities", []))
        n["tasks"] = len(body.get("tasks", []))
        steps = sum(len(a.get("steps", [])) for a in ld.get("activities", []))
        if steps:
            n["steps"] = steps
    elif model == "assessment-results":
        res = body.get("results", [])
        n["results"] = len(res)
        n["observations"] = sum(len(r.get("observations", [])) for r in res)
        n["findings"] = sum(len(r.get("findings", [])) for r in res)
    elif model == "profile":
        imps = body.get("imports", [])
        n["imports"] = len(imps)
        n["controls selected"] = sum(len(sel.get("with-ids", []))
                                     for i in imps for sel in i.get("include-controls", []))
        alters = (body.get("modify") or {}).get("alters", [])
        if alters:
            n["controls altered"] = len(alters)
            n["parts added"] = sum(len(ad.get("parts", []))
                                   for a in alters for ad in a.get("adds", []))
    elif model == "mapping-collection":
        maps = body.get("mappings", [])
        n["mappings"] = len(maps)
        n["maps"] = sum(len(m.get("maps", [])) for m in maps)
    return n


def title_of(body):
    return ((body.get("metadata") or {}).get("title") or "").strip()


#  Where a reader can open the document a row names. Two corpora are copied
#  into examples/ by tools/copy_examples.py and link to the copy; the third is
#  published in a public repository and links there, which is the rule that an
#  online document gets an online link.
#
#  Built here rather than in the renderer so the inventory carries the address
#  of every file it counts, and so a link that stops resolving is a data
#  difference the build can see rather than a click a reader has to try.
LINK_BASE = {
    "catalog-first":
        "https://github.com/awslabs/oscal-content-for-aws-services/blob/main/",
    "component-first": "examples/component-first/",
    "assessment-first": "examples/assessment-first/",
    "executable-first": "examples/executable-first/oscal/",
}


def scan(rel_root, under=None):
    base = os.path.join(under or CORPORA, rel_root)
    out = []
    for path in sorted(glob.glob(os.path.join(base, "**", "*.json"), recursive=True)):
        try:
            with open(path, encoding="utf-8") as fh:
                doc = json.load(fh)
        except Exception:
            continue
        if not isinstance(doc, dict) or not doc:
            continue
        model = next(iter(doc))
        if model not in MODEL_LABEL:
            continue          # not an OSCAL document; the XCCDF-derived JSON
        body = doc[model]
        out.append({
            "file": os.path.relpath(path, base).replace(os.sep, "/"),
            "model": model,
            "model_label": MODEL_LABEL[model],
            "title": title_of(body),
            "counts": summarise(model, body),
            "bytes": os.path.getsize(path),
            "href": None,          # filled in by build(), which knows the key
        })
    return out


def build():
    pubs = []
    for key, name, full, rel, repo, option in PUBLISHERS:
        files = (scan(rel) if rel
                 else scan(SITE_CORPORA[key], ROOT) if key in SITE_CORPORA else [])
        base = LINK_BASE[key]
        for f in files:
            #  A path in this repository, or a URL. quote() leaves the slashes
            #  alone and escapes the rest, which matters because two of these
            #  directories have spaces in their names.
            f["href"] = base + urllib.parse.quote(f["file"])
            f["href_external"] = base.startswith("http")
        by_model = collections.Counter(f["model"] for f in files)
        #  This corpus ships 230 component definitions, one per service.
        #  Listing every
        #  one would bury the catalog, which is the document the approach turns
        #  on, so the long tail is counted and a few are named.
        roll = None
        if key == "catalog-first":
            cdefs = [f for f in files if f["model"] == "component-definition"]
            keep = {"component-definitions/acm.oscal.json",
                    "component-definitions/cloudtrail.oscal.json",
                    "component-definitions/config.oscal.json",
                    "component-definitions/iam.oscal.json"}
            shown = [f for f in files if f["model"] != "component-definition"
                     or f["file"] in keep]
            roll = {
                "model_label": "Component definition",
                "count": len(cdefs),
                "components": sum(f["counts"].get("components", 0) for f in cdefs),
                "software": sum(f["counts"].get("software", 0) for f in cdefs),
                "note": ("One per service. Four are listed above as examples; "
                         "the rest follow the same shape."),
            }
            files = shown
        entry = {
            "key": key, "name": name, "full_name": full, "option": option,
            "repo": repo, "root": rel,
            "totals": {MODEL_LABEL[m]: c for m, c in sorted(by_model.items())},
            "files": files,
            "rollup": roll,
        }
        entry.update(UNPUBLISHED.get(key, {}))
        pubs.append(entry)
    return {
        "note": (__doc__ or "").strip().splitlines()[0],
        "publishers": pubs,
    }


def main():
    doc = build()
    text = json.dumps(doc, ensure_ascii=False, indent=2) + "\n"
    if "--check" in sys.argv:
        if not os.path.exists(OUT):
            sys.exit("data/oscal-artifacts.json is missing. Run tools/oscal_artifacts.py")
        if open(OUT, encoding="utf-8").read() != text:
            sys.exit("data/oscal-artifacts.json is stale. Run tools/oscal_artifacts.py")
        print("data/oscal-artifacts.json is current")
        return
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    for p in doc["publishers"]:
        print(f"  {p['name']:<16} {dict(p['totals'])}")


if __name__ == "__main__":
    main()
